global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
        labels:
          application: 'smart-task-manager'
          environment: 'development'
