spring:
  application:
    name: smart-task-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/smarttask
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Profile para desenvolvimento com H2
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /api

# SpringDoc OpenAPI (Swagger)
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: true

# Configurações JWT
jwt:
  secret: ${JWT_SECRET:sua-chave-secreta-muito-segura-aqui-mude-em-producao}
  expiration: 86400000 # 24 horas em millisegundos

# Configurações OpenAI
openai:
  api-key: ${OPENAI_API_KEY:your-api-key-here}
  model: gpt-4
  max-tokens: 500

# Configurações Twilio WhatsApp
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:}
  auth-token: ${TWILIO_AUTH_TOKEN:}
  whatsapp-number: ${TWILIO_WHATSAPP_NUMBER:}

# Configurações OpenTelemetry (via Spring Boot auto-configuration)
management:
  otlp:
    tracing:
      # Spring Boot 3.5 usa protocolo HTTP para OTLP por padrão (porta 4318), diferente do gRPC (porta 4317) usado em versões anteriores
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,traces
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
---
# Profile de desenvolvimento
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:


  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
